version: '3'
services:
  flask-api:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
  worker:
    build: .
    command: celery -A app.celery worker --loglevel=info --concurrency=2
    env_file:
      - .env
  monitor:
    build: .
    ports:
      - "5555:5555"
    command: flower -A app.celery --port=5555 --boker=redis://redis:6379/0
    depends_on:
      - redis
  redis:
    image: redis:alpine
